name:                CS111-AutoGrader
version:             0.1.0.0
github:              "levibutcher/CS111-AutoGrader"
license:             BSD3
author:              "Levi Butcher"
maintainer:          "levibutcher355@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/levibutcher/CS111-AutoGrader#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- regex-tdfa
- process
- cassava
- text
- bytestring

library:
  source-dirs: src

executables:
  CS111-AutoGrader-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CS111-AutoGrader

tests:
  CS111-AutoGrader-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CS111-AutoGrader
